# The answer is YES

In [1]:
import numpy as np

In [3]:
simpleArray = np.array([[1,2],[3,4]])
simpleArray

array([[1, 2],
       [3, 4]])

In [15]:
class SimpleClass:    
    def __init__(self, oneArray):
        self._array = oneArray
        self.BUG_NUM = 998877
        
    def modifyArray(self):
        self._array[0,0] = self.BUG_NUM

In [16]:
simpleInstance = SimpleClass(simpleArray)
simpleInstance._array

array([[1, 2],
       [3, 4]])

In [18]:
simpleInstance.modifyArray()
simpleInstance._array

array([[998877,      2],
       [     3,      4]])

In [19]:
simpleArray

array([[998877,      2],
       [     3,      4]])